FROM alpine:3.4

# 修改为国内镜像源
RUN echo "http://mirrors.aliyun.com/alpine/v3.4/main/" > /etc/apk/repositories

RUN apk update && apk upgrade \
  && apk add ca-certificates

RUN apk add cairo cairo-dev cairomm cairomm-dev pixman pixman-dev \
  jpeg jpeg-dev libjpeg libjpeg-turbo libjpeg-turbo-dev libpng \
  pango pango-dev pangomm pangomm-dev giflib giflib-dev  g++ \
  xproto renderproto kbproto xextproto freetype freetype-dev \
  git build-base nodejs-dev nodejs

RUN npm config set registry https://registry.npm.taobao.org --global
RUN npm install -g npm
RUN npm install -g node-gyp bower grunt-cli

RUN npm cache clear && rm -rf /var/cache/apk/*