FROM mhart/alpine-node:7.7.1

COPY entrypoint.sh /sbin/entrypoint.sh

RUN mkdir -p /root \
	&& node -v \
	&& npm config set registry https://registry.npm.taobao.org --global \
	&& echo "http://mirrors.aliyun.com/alpine/v3.5/main/" > /etc/apk/repositories \
	&& mkdir -p /root \
	&& chmod 755 /sbin/entrypoint.sh

EXPOSE 80
WORKDIR /wwwroot/htdocs/www
CMD ["/sbin/entrypoint.sh"]


