FROM mhart/alpine-node:7.7.1

COPY entrypoint.sh /sbin/entrypoint.sh

# 修改为国内镜像源
RUN echo "http://mirrors.aliyun.com/alpine/v3.5/main/" > /etc/apk/repositories

RUN apk update && apk upgrade \
  && apk add g++ cairo cairo-dev cairomm cairomm-dev pixman pixman-dev \
  jpeg jpeg-dev libjpeg libjpeg-turbo libjpeg-turbo-dev libpng \
  pango pango-dev pangomm pangomm-dev giflib giflib-dev  \
  xproto renderproto kbproto xextproto freetype freetype-dev \
  git build-base nodejs-dev \
  && rm -rf /var/cache/apk/* \
  && npm config set registry https://registry.npm.taobao.org --global \
  && npm install -g node-gyp bower grunt-cli \
  && npm cache clear \
  && chmod 755 /sbin/entrypoint.sh && mkdir -p /root && node -v

EXPOSE 80

CMD ["/sbin/entrypoint.sh"]
