FROM node:8-alpine

LABEL maintainer="ROCKY CHEN<rocky.cn@foxmail.com>"

# 修改为国内镜像源
#RUN echo 'https://mirrors.ustc.edu.cn/alpine/v3.7/main' > /etc/apk/repositories \
# && echo 'https://mirrors.ustc.edu.cn/alpine/v3.7/community' >> /etc/apk/repositories
RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.9/main' > /etc/apk/repositories \
 && echo 'http://dl-cdn.alpinelinux.org/alpine/v3.9/community' >> /etc/apk/repositories

EXPOSE 80
WORKDIR /wwwroot/htdocs/www

ADD entrypoint.sh /sbin/entrypoint.sh
ADD fonts.tar.bz2 /usr/share/fonts

# 修改了镜像源，需要更新证书
RUN apk update \
	&& apk upgrade \
	&& apk add --no-cache curl ca-certificates openssl \
	&& apk add --update ca-certificates openssl \
	&& update-ca-certificates \
  && \
apk add --no-cache zlib zlib-dev libcurl \
	   bash curl g++ cairo cairo-dev cairomm cairomm-dev pixman pixman-dev binutils-gold \
	   jpeg jpeg-dev libjpeg libjpeg-turbo libjpeg-turbo-dev libpng gnupg krb5-dev krb5-libs \
	   imagemagick-dev graphicsmagick-dev imagemagick graphicsmagick fontconfig libgcc \
	   pango pango-dev pangomm pangomm-dev giflib giflib-dev openssl-dev libstdc++ libgcrypt \
	   xproto renderproto kbproto xextproto freetype freetype-dev fontconfig-dev libgcrypt-dev \
	   bison flex gperf icu-dev libc-dev libpng-dev libx11-dev libxext-dev paxctl \
	   git build-base nodejs-dev gcc perl python ruby sqlite-dev linux-headers make \
    && \
apk add fontconfig mkfontscale wqy-zenhei \
    --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing --allow-untrusted \
    && \
mkdir -p /root \
  && node -v \
  && \
mkdir -p /usr/share \
  && cd /usr/share \
  && curl -L https://github.com/Overbryd/docker-phantomjs-alpine/releases/download/2.11/phantomjs-alpine-x86_64.tar.bz2 | tar xj \
  && ln -s /usr/share/phantomjs/phantomjs /usr/bin/phantomjs \
  && phantomjs --version \
  && \
npm install --production --unsafe-perm -g \
    node-gyp \
    bower \
    grunt-cli \
    canvas@1.6.2 \
    gulp-cli \
    cordova-hot-code-push-cli \
    pm2 \
    phantom@4.0.0 \
    hiredis@0.4.1 \
    kerberos@0.0.21 \
    && npm config set registry https://registry.npm.taobao.org --global \
    && \
npm cache clear --force \
    && chmod 755 /sbin/entrypoint.sh \
    && rm -rf /tmp/* \
        /var/cache/apk/* \
        /root/.gnupg \
        /usr/lib/node_modules/npm/doc \
        /usr/lib/node_modules/npm/html

