#FROM mhart/alpine-node:7.7.1
FROM mhart/alpine-node:base-7.7.1

COPY entrypoint.sh /sbin/entrypoint.sh

RUN apk update && apk upgrade \
  && rm -rf /var/cache/apk/* \
  && chmod 755 /sbin/entrypoint.sh && mkdir -p /root && node -v

EXPOSE 80

CMD ["/sbin/entrypoint.sh"]
