FROM alpine:3.10

ENV LANG=en_US.UTF-8
ENV VERSION=v10.16.2 NPM_VERSION=6.9.0 YARN_VERSION=latest
# ENV VERSION=v10.4.1 NPM_VERSION=6 YARN_VERSION=latest

# 修改为国内镜像源
#RUN echo 'https://mirrors.ustc.edu.cn/alpine/v3.7/main' > /etc/apk/repositories \
# && echo 'https://mirrors.ustc.edu.cn/alpine/v3.7/community' >> /etc/apk/repositories

RUN echo 'http://dl-cdn.alpinelinux.org/alpine/v3.10/main' > /etc/apk/repositories \
 && echo 'http://dl-cdn.alpinelinux.org/alpine/v3.10/community' >> /etc/apk/repositories

ADD fonts.tar.bz2 /usr/share/fonts
ADD entrypoint.sh /sbin/entrypoint.sh

EXPOSE 80
WORKDIR /wwwroot/htdocs/www
ENTRYPOINT ["/sbin/entrypoint.sh"]

# 修改了镜像源，需要更新证书
RUN apk update \
	&& apk upgrade \
	&& apk add --no-cache curl ca-certificates openssl \
	&& apk add --update ca-certificates openssl \
	&& update-ca-certificates \
  && \
apk add --no-cache bash make gcc g++ libstdc++ imagemagick graphicsmagick fontconfig \
		python linux-headers libnsl libnsl-dev git zlib zlib-dev libcurl libjpeg-turbo-dev \
		nodejs nodejs-npm yarn cairo cairomm cairo-dev cairomm-dev pixman jpeg-dev \
		jpeg libjpeg libjpeg-turbo libpng libgcrypt pango-dev pangomm-dev libpng-dev \
		pango pangomm giflib giflib-dev freetype krb5-libs krb5-dev \
    && \
apk add --no-cache --virtual=.build-dependencies \
		binutils-gold gnupg imagemagick-dev sqlite-libs gnutls \
		nodejs-dev pixman-dev openssl-dev gnutls-dev icu-libs \
		xproto renderproto kbproto xextproto freetype-dev fontconfig-dev \
		bison flex gperf icu-dev libc-dev  libx11-dev libxext-dev \
		build-base perl ruby sqlite-dev graphicsmagick-dev \
		keyutils-libs libcom_err musl-dev libgpg-error nss-dev libgcc expat \
		libssl1.0 libcrypto1.0 libgcrypt-dev libffi heimdal-libs paxctl \
		libldap libtasn1 librtmp libsasl cyrus-sasl-dev libidn p11-kit \
    && \
apk add fontconfig mkfontscale wqy-zenhei \
    --update-cache --repository http://dl-3.alpinelinux.org/alpine/edge/testing --allow-untrusted \
    && \
mkdir -p /root \
	&& node -v \
  && \
mkdir -p /usr/share \
  && cd /usr/share \
  && curl -L https://github.com/Overbryd/docker-phantomjs-alpine/releases/download/2.11/phantomjs-alpine-x86_64.tar.bz2 | tar xj \
  && ln -s /usr/share/phantomjs/phantomjs /usr/bin/phantomjs \
  && phantomjs --version \
  && \
npm install --production --unsafe-perm -g \
    node-gyp \
    bower \
    grunt-cli \
    canvas@1.6.2 \
    gulp-cli \
    cordova-hot-code-push-cli \
    pm2 \
    phantom@4.0.0 \
    hiredis@0.4.1 \
    kerberos@0.0.21 \
    && npm config set registry https://registry.npm.taobao.org --global
    && \
apk del .build-dependencies \
    && npm cache clear --force \
    && chmod 755 /sbin/entrypoint.sh \
    && rm -rf /tmp/* \
        /var/cache/apk/* \
        /root/.gnupg \
        /usr/lib/node_modules/npm/doc \
        /usr/lib/node_modules/npm/html

