FROM mhart/alpine-node:7.7.1

COPY entrypoint.sh /sbin/entrypoint.sh
COPY fonts.tar.bz2 /tmp/fonts.tar.bz2
COPY hello.js /tmp/hello.js
COPY phantomjs-2.1.1-linux-x86_64.tar.bz2 /tmp/phantomjs-2.1.1-linux-x86_64.tar.bz2

RUN mkdir -p /usr/share/fonts \
	&& tar -xjvf /tmp/fonts.tar.bz2 -C /usr/share/fonts

RUN apk update \
	&& apk upgrade \
	&& apk add --no-cache curl ca-certificates openssl \
	&& apk add --update ca-certificates openssl \
	&& update-ca-certificates

RUN apk add --no-cache \
		curl g++ cairo cairo-dev cairomm cairomm-dev pixman pixman-dev binutils-gold \
		jpeg jpeg-dev libjpeg libjpeg-turbo libjpeg-turbo-dev libpng gnupg \
		pango pango-dev pangomm pangomm-dev giflib giflib-dev openssl-dev libstdc++ \
		xproto renderproto kbproto xextproto freetype freetype-dev fontconfig-dev \
		bison flex gperf icu-dev libc-dev libpng-dev libx11-dev libxext-dev paxctl \
		git build-base nodejs-dev gcc perl python ruby sqlite-dev linux-headers make \
		libc6-compat \
		keyutils-libs \
		libcom_err \
		musl-dev \
		libgpg-error \
		nss-dev \
		libgcc \
		zlib \
		expat \
		libssl1.0 \
		libcrypto1.0 \
		libgcrypt \
		libgcrypt-dev \
		libffi \
		heimdal-libs \
		krb5-libs \
		libldap \
		libtasn1 \
		librtmp \
		libsasl \
		cyrus-sasl-dev \
		libidn \
		fontconfig \
		p11-kit \
		libcurl \
		sqlite-libs \
		gnutls \
		gnutls-dev \
		icu-libs \
	&& mkdir -p /root \
	&& node -v

RUN cd /tmp && tar -xjvf phantomjs-2.1.1-linux-x86_64.tar.bz2 \
	&& chmod 755 /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs

RUN cp /tmp/phantomjs-2.1.1-linux-x86_64/bin/phantomjs /usr/bin/phantomjs

RUN npm install -g node-gyp bower grunt-cli canvas@1.6.2 gulp-cli cordova-hot-code-push-cli \
	&& chmod 755 /sbin/entrypoint.sh

RUN npm cache clear \
	&& rm -rf /tmp/* /var/cache/apk/* /root/.gnupg /usr/lib/node_modules/npm/doc /usr/lib/node_modules/npm/html \
	&& npm config set registry https://registry.npm.taobao.org --global \
	&& echo "http://mirrors.aliyun.com/alpine/v3.5/main/" > /etc/apk/repositories \
	&& mkdir -p /root
	
EXPOSE 80

CMD ["/sbin/entrypoint.sh"]
