FROM registry.cn-hangzhou.aliyuncs.com/joinin/base

RUN apk update && apk upgrade && apk add cairo cairo-dev \
  cairomm cairomm-dev pixman pixman-dev \
  jpeg jpeg-dev libjpeg libjpeg-turbo libjpeg-turbo-dev libpng \
  pango pango-dev pangomm pangomm-dev giflib giflib-dev  g++ \
  xproto renderproto kbproto xextproto freetype freetype-dev \
  git build-base nodejs-dev nodejs

RUN npm install -g npm
RUN npm install -g node-gyp bower grunt-cli
RUN npm config set registry https://registry.npm.taobao.org --global
RUN npm cache clear && rm -rf /var/cache/apk/*